#!/bin/sh

#this is horrible lmao

i="intro functions constants stdtypes exceptions text binary string re difflib textwrap unicodedata stringprep readline rlcompleter struct codecs datetime zoneinfo calendar collections collections.abc heapq bisect array weakref types copy pprint reprlib enum graphlib numeric numbers math cmath decimal fractions random statistics functional itertools functools operator filesys pathlib os.path fileinput stat filecmp tempfile glob fnmatch linecache shutil persistence pickle copyreg shelve marshal dbm sqlite3 archiving zlib gzip bz2 lzma zipfile tarfile fileformats csv configparser netrc xdrlib plistlib crypto hashlib hmac secrets allos os io time argparse getopt logging logging.config logging.handlers getpass curses curses.textpad curses.ascii curses.panel platform errno ctypes concurrency threading multiprocessing multiprocessing.shared_memory concurrent concurrent.futures subprocess sched queue contextvars _thread ipc asyncio socket ssl select selectors asyncore asynchat signal mmap netdata email json mailcap mailbox mimetypes base64 binhex binascii quopri uu markup html html.parser html.entities xml xml.etree.ElementTree xml.dom xml.dom.minidom xml.dom.pulldom xml.sax xml.sax.handler xml.sax.saxutils xml.sax.xmlreader xml.parsers.expat internet webbrowser cgi cgitb wsigiref urllib urllib.request urllib.response urllib.parse urllib.error urllib.robotparser http http.client ftplib poplib imaplib nntplib smtplib smtpd telnetlib uuid socketserver http.server http.cookies http.cookiejar xmlrpc xmlrpc.client xmlrpc.server ipaddress mm audioop aifc sunau wave chunk colorsys imghdr sndhdr ossaudiodev i18n gettext locale frameworks turtle cmd shlex tk tkinter tkinter.colorchooser tkinter.font dialog tkinter.messagebox tkinter.scrolledtext tkinter.dnd tkinter.ttk tkinter.tix idle development typing pydoc devmode doctest unittest unittest.mock unittest.mock-examples 2to3 test debug audit_events bdb faulthandler pdb profile timeit trace tracemalloc distribution distutils ensurepip venv zipapp python sys sysconfig builtins __main__ warnings dataclasses contextlib abc atexit traceback __future__ gc inspect site custominterp code codeop omdules zipimport pkgutil modulefinder runpy importlib importlib.metadata language ast symtable token keyword tokenize tabnanny pyclbr py_compile compileall dis pickletools windows msilib msvcrt winreg winsound unix posix pwd spwd grp crypt termios tty pty fcntl pipes resource nis syslog superseded optparse imp undoc security_warnings"

for x in $i; do
    nc-get "https://docs.python.org/3/library/$x.html" && echo "$x downloaded" &
    #echo "https://docs.python.org/3/library/$x.html"
done

wait
